# Generated by Django 5.2.3 on 2025-07-19 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pareja",
            fields=[
                ("numero_pareja", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(null=True)),
                (
                    "miembro_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parejas_como_1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "miembro_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parejas_como_2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
